apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- postgres-secret.yaml
namespace: api-dev
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.local
  target:
    kind: Ingress
    name: agrocd-api
images:
- name: agrocd-api
  newName: ghcr.io/nickpeachey/agrocd-api
  newTag: d58deb4
- name: agrocd-db-migrator
  newName: ghcr.io/nickpeachey/agrocd-db-migrator
  newTag: d58deb4
